use utoipa::OpenApi;

/// Aggregates every `#[utoipa::path]`-annotated handler and every schema
/// type referenced by a request/response body into one OpenAPI document,
/// served at `GET /api/openapi.json` (see `lib.rs`) and browsable at
/// `/api/docs`. Manually maintained rather than auto-collected (see
/// `.ai/decisions/current/2026-08-27-api-contract-utoipa-orval-react-query.md`
/// for why): `utoipa`'s `paths(...)` macro fails to compile if a listed
/// handler is missing its `#[utoipa::path]` annotation, so a forgotten
/// entry is caught at compile time, not silently.
#[derive(OpenApi)]
#[openapi(
    paths(
        crate::routes::auth::signup,
        crate::routes::auth::login,
        crate::routes::auth::client_login,
        crate::routes::auth::logout,
        crate::routes::auth::me,
        crate::routes::auth::create_teammate,
        crate::routes::auth::revoke_user_sessions,
        crate::routes::auth::set_tenant_admin,
        crate::routes::platform::platform_login,
        crate::routes::platform::list_tenants,
        crate::routes::platform::pause_tenant,
        crate::routes::platform::resume_tenant,
        crate::routes::platform::delete_tenant,
        crate::routes::business_units::create_business_unit,
        crate::routes::business_units::list_business_units,
        crate::routes::business_units::assign_role,
        crate::routes::business_units::list_roles,
        crate::routes::clients::create_client,
        crate::routes::clients::create_client_user,
        crate::routes::clients::list_clients,
        crate::routes::leads::create_lead,
        crate::routes::leads::list_leads,
        crate::routes::leads::convert_lead,
        crate::routes::projects::create_project,
        crate::routes::projects::get_project,
        crate::routes::projects::list_projects,
        crate::routes::quotations::create_quotation,
        crate::routes::quotations::list_quotations,
        crate::routes::quotations::get_quotation,
        crate::routes::change_orders::create_change_order,
        crate::routes::change_orders::list_change_orders,
        crate::routes::change_orders::get_change_order,
        crate::routes::design::create_design_asset,
        crate::routes::design::list_design_assets,
        crate::routes::design::submit_design_revision,
        crate::routes::design::list_design_revisions,
        crate::routes::procurement::create_vendor,
        crate::routes::procurement::list_vendors,
        crate::routes::procurement::create_purchase_order,
        crate::routes::procurement::list_purchase_orders,
        crate::routes::procurement::approve_purchase_order,
        crate::routes::procurement::reject_purchase_order,
        crate::routes::procurement::mark_purchase_order_delivered,
        crate::routes::manufacturing::create_production_task,
        crate::routes::manufacturing::list_production_tasks,
        crate::routes::manufacturing::update_production_task_status,
        crate::routes::site_execution::create_site_task,
        crate::routes::site_execution::list_site_tasks,
        crate::routes::site_execution::update_site_task_status,
        crate::routes::site_execution::create_daily_log,
        crate::routes::site_execution::list_daily_logs,
        crate::routes::site_execution::create_punch_list_item,
        crate::routes::site_execution::list_punch_list_items,
        crate::routes::site_execution::close_punch_list_item,
        crate::routes::site_execution::create_site_query,
        crate::routes::site_execution::list_site_queries,
        crate::routes::site_execution::answer_site_query,
        crate::routes::schedule::create_schedule_task,
        crate::routes::schedule::list_schedule_tasks,
        crate::routes::schedule::update_schedule_task_status,
        crate::routes::schedule::update_schedule_task_dates,
        crate::routes::schedule::add_schedule_task_dependency,
        crate::routes::schedule::list_schedule_task_dependencies,
        crate::routes::billing::create_milestone,
        crate::routes::billing::list_milestones,
        crate::routes::billing::complete_milestone,
        crate::routes::billing::create_invoice,
        crate::routes::billing::list_invoices,
        crate::routes::billing::mark_invoice_paid,
        crate::routes::notifications::list_my_notifications,
        crate::routes::notifications::mark_notification_read,
        crate::routes::tenant_settings::get_tenant_settings,
        crate::routes::tenant_settings::update_tenant_settings,
        crate::routes::client_portal::list_my_projects,
        crate::routes::client_portal::list_project_design_assets,
        crate::routes::client_portal::approve_design_revision,
        crate::routes::client_portal::reject_design_revision,
        crate::routes::client_portal::approve_quotation,
        crate::routes::client_portal::reject_quotation,
        crate::routes::client_portal::list_my_change_orders,
        crate::routes::client_portal::approve_change_order,
        crate::routes::client_portal::reject_change_order,
        crate::routes::client_portal::list_project_invoices,
    ),
    components(schemas(
        crate::error::ErrorResponse,
        // Entity models referenced in response bodies.
        entity::business_unit::Model,
        entity::change_order::Model,
        entity::change_order_line_item::Model,
        entity::change_order_schedule_task::Model,
        entity::change_order_workstream::Model,
        entity::client::Model,
        entity::client_user::Model,
        entity::daily_log::Model,
        entity::design_asset::Model,
        entity::design_revision::Model,
        entity::invoice::Model,
        entity::lead::Model,
        entity::milestone::Model,
        entity::notification::Model,
        entity::production_task::Model,
        entity::project::Model,
        entity::project_workstream::Model,
        entity::punch_list_item::Model,
        entity::purchase_order::Model,
        entity::purchase_order_line_item::Model,
        entity::quotation::Model,
        entity::quotation_line_item::Model,
        entity::schedule_task::Model,
        entity::schedule_task_dependency::Model,
        entity::site_query::Model,
        entity::site_task::Model,
        entity::tenant::Model,
        entity::user::Model,
        entity::user_business_unit_role::Model,
        entity::vendor::Model,
        entity::workstream_type::WorkstreamType,
        // Route-local request/response DTOs.
        crate::routes::auth::SignupRequest,
        crate::routes::auth::SignupResponse,
        crate::routes::auth::LoginRequest,
        crate::routes::auth::CreateTeammateRequest,
        crate::routes::auth::SetTenantAdminRequest,
        crate::routes::auth::MeResponse,
        crate::routes::platform::PlatformLoginRequest,
        crate::routes::platform::TenantSummary,
        crate::routes::business_units::CreateBusinessUnitRequest,
        crate::routes::business_units::AssignRoleRequest,
        crate::routes::clients::CreateClientRequest,
        crate::routes::clients::CreateClientUserRequest,
        crate::routes::leads::CreateLeadRequest,
        crate::routes::leads::ConvertLeadRequest,
        crate::routes::leads::ConvertedProjectResponse,
        crate::routes::projects::CreateProjectRequest,
        crate::routes::projects::ProjectResponse,
        crate::routes::quotations::LineItemInput,
        crate::routes::quotations::CreateQuotationRequest,
        crate::routes::quotations::QuotationResponse,
        crate::routes::change_orders::ChangeLineItemInput,
        crate::routes::change_orders::CreateChangeOrderRequest,
        crate::routes::change_orders::NewScheduleTaskInput,
        crate::routes::change_orders::ChangeOrderResponse,
        crate::routes::design::CreateDesignAssetRequest,
        crate::routes::design::SubmitRevisionRequest,
        crate::routes::design::DesignAssetWithRevisions,
        crate::routes::procurement::CreateVendorRequest,
        crate::routes::procurement::PoLineItemInput,
        crate::routes::procurement::CreatePurchaseOrderRequest,
        crate::routes::procurement::PurchaseOrderResponse,
        crate::routes::procurement::PoDecisionRequest,
        crate::routes::manufacturing::CreateProductionTaskRequest,
        crate::routes::manufacturing::UpdateStatusRequest,
        crate::routes::site_execution::CreateSiteTaskRequest,
        crate::routes::site_execution::SiteTaskResponse,
        crate::routes::site_execution::UpdateStatusRequest,
        crate::routes::site_execution::CreateDailyLogRequest,
        crate::routes::site_execution::CreatePunchListItemRequest,
        crate::routes::site_execution::CreateSiteQueryRequest,
        crate::routes::site_execution::AnswerSiteQueryRequest,
        crate::routes::schedule::CreateScheduleTaskRequest,
        crate::routes::schedule::UpdateScheduleTaskStatusRequest,
        crate::routes::schedule::UpdateDatesRequest,
        crate::routes::schedule::UpdateDatesResponse,
        crate::routes::schedule::AddScheduleDependencyRequest,
        crate::routes::billing::CreateMilestoneRequest,
        crate::routes::billing::CreateInvoiceRequest,
        crate::routes::tenant_settings::TenantSettingsResponse,
        crate::routes::tenant_settings::UpdateTenantSettingsRequest,
        crate::routes::client_portal::DecisionRequest,
    )),
    tags(
        (name = "auth", description = "Signup, login, session/user management"),
        (name = "platform", description = "Platform-admin tenant lifecycle (pause/resume/delete)"),
        (name = "business_units", description = "Business units and role assignment"),
        (name = "clients", description = "Client companies and Client Portal logins"),
        (name = "leads", description = "Pre-sales leads and conversion to projects"),
        (name = "projects", description = "Projects and their enabled workstreams"),
        (name = "quotations", description = "Versioned BOQ quotations"),
        (name = "change_orders", description = "Scope-change requests requiring client approval"),
        (name = "design", description = "Design assets and versioned revisions"),
        (name = "procurement", description = "Vendors and purchase orders"),
        (name = "manufacturing", description = "Production task tracking"),
        (name = "site_execution", description = "Site tasks, daily logs, punch list, site queries"),
        (name = "schedule", description = "Cross-workstream schedule task/dependency graph"),
        (name = "billing", description = "Milestones and invoices"),
        (name = "notifications", description = "In-app notifications"),
        (name = "tenant_settings", description = "Tenant-level configuration"),
        (name = "client_portal", description = "Client Portal read/approve surface"),
    )
)]
pub struct ApiDoc;
